[CmdletBinding()]
param (
    [string]$CollectionName = "coll1",
    [string]$MT4BrokerName = "afterprime",
    [string]$MT5BrokerName = "afterprime",
    [string]$StrategyName = "DefaultStrategy"
)

# Ensure script runs from its own directory
Set-Location -Path $PSScriptRoot

# Helper Function
function Write-Status { param ([string]$Message, [string]$Color = "Yellow") Write-Host $Message -ForegroundColor $Color }

function Cleanup-Environment {
    param (
        [string]$CollectionName,
        [string]$MT4BrokerName,
        [string]$MT5BrokerName,
        [string]$StrategyName
    )

    Write-Status "Starting cleanup of MT Trading Framework environment..." "Cyan"

    # Define the BasePath
    $basePath = "C:\Trading\MTFramework"

    # Ensure BasePath exists before writing files
    if (-not (Test-Path $basePath)) {
        New-Item -Path $basePath -ItemType Directory -Force | Out-Null
        Write-Status "Created BasePath directory: $basePath" "Green"
    }

    # Reset setup.json to the latest configuration
    $setupFile = Join-Path -Path $PSScriptRoot -ChildPath "setup.json"
    $defaultSetup = @{
        BasePath = "C:\Trading\MTFramework"
        StrategyCollections = @(
            @{
                CollectionName = $CollectionName
                StrategyName = $StrategyName
                SkipDocker = $true
                Platforms = @(
                    @{
                        Platform = "MT4"
                        BrokerName = $MT4BrokerName
                        ExplicitPath = ""
                        Environments = @("Dev", "Test", "Deploy")
                    },
                    @{
                        Platform = "MT5"
                        BrokerName = $MT5BrokerName
                        ExplicitPath = ""
                        Environments = @("Dev", "Test", "Deploy")
                    }
                )
            }
        )
    }
    try {
        $defaultSetup | ConvertTo-Json -Depth 10 | Set-Content -Path $setupFile
        Write-Status "Reset setup file to latest configuration: $setupFile" "Green"
    } catch {
        Write-Status "Failed to reset setup.json: $($_.Exception.Message)" "Red"
    }

    # Reset build.json to empty state (to be regenerated by MTSetup.ps1)
    $buildFile = Join-Path -Path $basePath -ChildPath "build.json"
    $defaultBuild = @{
        BasePath = $basePath
        StrategyCollections = @()
    }
    try {
        $defaultBuild | ConvertTo-Json -Depth 10 | Set-Content -Path $buildFile
        Write-Status "Reset build file to default: $buildFile" "Green"
    } catch {
        Write-Status "Failed to reset build.json: $($_.Exception.Message)" "Red"
    }

    # Delete the MT4 collection folder
    $mt4CollectionPath = Join-Path -Path $basePath -ChildPath "MT4\$MT4BrokerName\$CollectionName"
    if (Test-Path $mt4CollectionPath) {
        Remove-Item -Path $mt4CollectionPath -Recurse -Force -ErrorAction SilentlyContinue
        Write-Status "Removed MT4 collection folder: $mt4CollectionPath" "Green"
    } else {
        Write-Status "MT4 collection folder not found at: $mt4CollectionPath" "Yellow"
    }

    # Delete the MT5 collection folder
    $mt5CollectionPath = Join-Path -Path $basePath -ChildPath "MT5\$MT5BrokerName\$CollectionName"
    if (Test-Path $mt5CollectionPath) {
        Remove-Item -Path $mt5CollectionPath -Recurse -Force -ErrorAction SilentlyContinue
        Write-Status "Removed MT5 collection folder: $mt5CollectionPath" "Green"
    } else {
        Write-Status "MT5 collection folder not found at: $mt5CollectionPath" "Yellow"
    }

    # Clean up Desktop shortcuts
    $desktopPath = [System.Environment]::GetFolderPath("Desktop")
    
    # Clean up MT4 shortcuts
    $mt4BrokerFolder = Join-Path -Path $desktopPath -ChildPath $MT4BrokerName
    if (Test-Path $mt4BrokerFolder) {
        $mt4Shortcuts = Get-ChildItem -Path $mt4BrokerFolder -Filter "MT4 - $MT4BrokerName [$CollectionName-$StrategyName]*.lnk" -ErrorAction SilentlyContinue
        if ($mt4Shortcuts) {
            foreach ($shortcut in $mt4Shortcuts) {
                Remove-Item -Path $shortcut.FullName -Force -ErrorAction SilentlyContinue
                Write-Status "Removed MT4 shortcut: $($shortcut.Name)" "Green"
            }
            # Remove the broker folder if empty
            if (-not (Get-ChildItem -Path $mt4BrokerFolder)) {
                Remove-Item -Path $mt4BrokerFolder -Force -ErrorAction SilentlyContinue
                Write-Status "Removed empty MT4 broker folder: $mt4BrokerFolder" "Green"
            }
        } else {
            Write-Status "No MT4 shortcuts found in: $mt4BrokerFolder" "Yellow"
        }
    } else {
        Write-Status "MT4 broker folder not found at: $mt4BrokerFolder" "Yellow"
    }

    # Clean up MT5 shortcuts
    $mt5BrokerFolder = Join-Path -Path $desktopPath -ChildPath $MT5BrokerName
    if (Test-Path $mt5BrokerFolder) {
        $mt5Shortcuts = Get-ChildItem -Path $mt5BrokerFolder -Filter "MT5 - $MT5BrokerName [$CollectionName-$StrategyName]*.lnk" -ErrorAction SilentlyContinue
        if ($mt5Shortcuts) {
            foreach ($shortcut in $mt5Shortcuts) {
                Remove-Item -Path $shortcut.FullName -Force -ErrorAction SilentlyContinue
                Write-Status "Removed MT5 shortcut: $($shortcut.Name)" "Green"
            }
            # Remove the broker folder if empty
            if (-not (Get-ChildItem -Path $mt5BrokerFolder)) {
                Remove-Item -Path $mt5BrokerFolder -Force -ErrorAction SilentlyContinue
                Write-Status "Removed empty MT5 broker folder: $mt5BrokerFolder" "Green"
            }
        } else {
            Write-Status "No MT5 shortcuts found in: $mt5BrokerFolder" "Yellow"
        }
    } else {
        Write-Status "MT5 broker folder not found at: $mt5BrokerFolder" "Yellow"
    }

    Write-Status "Cleanup completed." "Green"
}

# Execute cleanup
try {
    Cleanup-Environment -CollectionName $CollectionName -MT4BrokerName $MT4BrokerName -MT5BrokerName $MT5BrokerName -StrategyName $StrategyName
} catch {
    Write-Status "Cleanup failed: $($_.Exception.Message)" "Red"
    exit
}